/*
*	THIS FILE IS GENERATED BY A SCRIPT
*	Modify sinTableCreator2.py to change, otherwise it will be changed during the next build
*/
#ifndef SIN_TABLE
#define SIN_TABLE

//Note: sin values are defined for powers of 2 from 2^1 to 2^%(power)s = %(maxValue)s

float sin(unsigned int x);

#endif
